<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Post;

class PostsTableSeeder extends Seeder
{
    public function run()
    {
        $json = '[{"id":"37766245-9338-451e-87a8-bab140860070","title":"Bruno León (Activista Trans) | Transexualidad, veganismo y más","body":"Hoy tenemos a Bruno León con quién aprenderemos y escucharemos la historia de una persona trans","type":"podcast","url":"https:\/\/open.spotify.com\/embed\/episode\/10dOWUhvVWTwS5ynojjAqt?utm_source=generator","image":"https:\/\/i.scdn.co\/image\/ab6765630000ba8ab76ffafb73ee09b9227a1ce9","author":"Ibai Vegan","author_id":"f1506ee9-7002-41ec-85a3-d78dab6ab2e9","language":"ES","created_at":"2024-04-09 12:25:29","updated_at":"2024-04-09 12:25:29"},
{"id":"4130fed5-2fa7-46e6-9e79-292b05225aca","title":"Las 5 acciones que más reducirían el impacto medioambiental de los españoles","body":"A veces parece que vivimos en el día de la marmota. No hace ni 3 meses que estaba escribiendo sobre cómo evitar olas de calor a corto plazo. Más de 500 muertes. Más de 30 incendios. Así llevamos la ola de calor de julio. ¿Desolador? Sin duda. Pero en medio de todas las emociones sigue la acción y la ciencia. Varios estudios muestran que estas situaciones extremas son el punto de inflexión que mucha gente necesita para empezar a actuar. Para todas esas personas escribo este artículo. Una recopilación de las acciones más importantes. ¿Y cómo sé que son las más importantes? Porque me voy a basar en los datos. Concretamente la referencia de este artículo es el Informe de Sostenibilidad de Consumo de España (2022). Cómo por ahora ningún gobierno me ha pedido un informe de las medidas efectivas, lo que te voy a proponer son las acciones que podemos poner en práctica la gente corriente.","type":"webpage","url":"https:\/\/www.barbarapgs.com\/blog\/las-5-acciones-que-ms-reduciran-el-impacto-medioambiental-de-los-espaoles","image":"https:\/\/images.squarespace-cdn.com\/content\/v1\/622f84208feb0027729013ad\/929a2570-105e-43cf-b0d3-99ecd4c5031f\/grafico_sectores.jpg?format=2500w","author":"Bárbara González","author_id":"12e8a3e3-193d-4a93-8e9d-10d56a074947","language":"ES","created_at":"2024-04-09 12:25:47","updated_at":"2024-04-09 12:25:47"},
{"id":"560b08d9-12d0-46ed-b507-5e1647a73475","title":"Entrevista a Irene Montero","body":"La invitada 142 del Podcast es la política y ex Ministra de Igualdad Irene Montero. En esta entrevista tenemos una política que no deja indiferente a nadie, llegó con el anterior gobierno de España a ser Ministra de igualdad. Primera vez que hay un ministerio de igualdad y un gobierno de coalición, nos contará cómo lo ha vivido desde dentro. Le montaron otro partido acercándose las elecciones, el partido “Sumar” liderado por Yolanda Díaz, cómo lo vivió? Cuál es su relación con ella? Además, pusieron como requisito para las elecciones donde iban Sumar y Podemos, que ella, Irene Montero, no estuviera en las listas. ¿Cuál fue el motivo y quien lo decidió así? Una entrevista donde conocer el lado mas personal de Irene, pero también donde le preguntaremos por temas polémicos y leyes polémicas como la del “sólo el Si es Si” o la “ley trans”.","type":"youtube","url":"https:\/\/www.youtube.com\/embed\/tgOxJKKarV8?si=i9Knm8kfTolDo-CX","image":"https:\/\/i.ytimg.com\/vi\/tgOxJKKarV8\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&amp;rs=AOn4CLD5J3sjlwXs6sSs4niOHWYaZUrGJw","author":"Ibai Vegan","author_id":"f1506ee9-7002-41ec-85a3-d78dab6ab2e9","language":"ES","created_at":"2024-04-09 12:26:50","updated_at":"2024-04-09 12:26:50"},
{"id":"752f65f8-3c76-47ad-a34b-b8636a38b96f","title":"Mascletá en Madrid","body":"Ningún ser inteligente destrozaría el planeta donde vive. No solo no nos ponemos a protegerlo sino que cada día destrozamos más y más y más la naturaleza y a todos sus habitantes. Vergüenza de toda la gente que lleva banderitas pero está destruyendo su tierra; patriota es quien defiende su tierra, quien destruye su tierra es antipatriota","type":"instagram","url":"https:\/\/www.tiktok.com\/@xavi.animal\/video\/7337017354112568581","image":"https:\/\/www.instagram.com\/reel\/C3fWFBQtlS6\/?igsh=MWJpZzh3eW5wdWxyZA==","author":"Xavi Animal","author_id":"5f12cf40-8d27-4f48-b947-b07ce52880a9","language":"ES","created_at":"2024-04-09 12:26:16","updated_at":"2024-04-09 12:26:16"},
{"id":"7f2438fe-1cbb-48c9-abca-96f2e49d5da4","title":"Santuarios y antiespecismo con Laura Luengo","body":"Hoy, en Sostenibilidad Interseccional, charlamos con Laura Luengo, fundadora de un santuario para animales considerados de granja. Hablaremos sobre el especismo y la situación que viven algunos animales.","type":"podcast","url":"https:\/\/open.spotify.com\/embed\/episode\/6joYMxhPJz8XNJ8GMkaz2y?utm_source=generator","image":"https:\/\/i.scdn.co\/image\/ab67656300005f1f44def045391697ad0e51a138","author":"Bárbara González","author_id":"12e8a3e3-193d-4a93-8e9d-10d56a074947","language":"ES","created_at":"2024-06-23 18:41:09","updated_at":"2024-06-23 18:41:09"},
{"id":"8a1b1658-259c-40fc-8969-3b72ddf3a7e1","title":"Zero Waste para salvar el mundo","body":"El planeta está al límite. Nos hallamos cerca de lo que los científicos llaman el «punto de no retorno». Es necesario que tomemos conciencia de ello y nos pongamos en acción para salvarlo. El movimiento Zero Waste promueve un estilo de vida más sostenible para reducir nuestro impacto medioambiental y generar los mínimos residuos posibles. Y Zero Waste para salvar el mundo es la primera guía ilustrada que ofrece trucos y consejos sencillos para poner en práctica en todos los ámbitos del día a día: cómo reciclar los residuos, cómo hacer la compra de una manera más sostenible, qué objetos debemos eliminar de nuestra rutina, cuál es el kit básico para tener una cocina más respetuosa con el medio ambiente.","type":"libro","url":"https:\/\/www.goodreads.com\/book\/show\/52857961-zero-waste-para-salvar-el-mundo?from_search=true&from_srp=true&qid=k35DNSVchf&rank=2","image":"https:\/\/images-na.ssl-images-amazon.com\/images\/S\/compressed.photo.goodreads.com\/books\/1567672469l\/52857961.jpg","author":"Ally Vispo","author_id":"e0da729b-5e05-43c3-a09f-19d909faa25e","language":"ES","created_at":"2024-06-23 18:34:20","updated_at":"2024-06-23 18:34:20"},
{"id":"a62deeb5-0ad0-4c8c-96b3-4ceba2917950","title":"Nunca verás tu vida de la misma manera - Discurso que te abrirá los ojos","body":"Mira el discurso que fue dado a miles de estudiantes en universidades del Reino Unido.","type":"youtube","url":"https:\/\/www.youtube.com\/embed\/Z3u7hXpOm58?si=3oMl-MPg65FE5Wyl","image":"https:\/\/i.ytimg.com\/vi\/Z3u7hXpOm58\/hqdefault.jpg?s…AFwAcABBg==&rs=AOn4CLAbfO7-oOFBlohJBXjCbvrIX6lKaw","author":"Earthling Ed","author_id":"bfb6735a-dbb8-49d6-b0fd-1fe0e613c6dd","language":"EN","created_at":"2024-04-09 12:27:06","updated_at":"2024-04-09 12:27:06"},
{"id":"aa7e52d9-40c5-4d71-87b6-3fb01b9db1cc","title":"Okja","body":"Mija (Ahn Seo-hyeon), una niña que vive en una montaña remota en Gangwon, se embarca en un arriesgado viaje a Nueva York para rescatar a su mejor amiga, una supercerda llamada Okja, de las manos de Mirando Corporation, una multinacional que ambiciona convertirla en carne. En el trayecto, obtendrá ayuda de unos activistas por los derechos de los animales del Frente de Liberación Animal que están en contra de los planes de la corporación.","type":"película","url":"https:\/\/www.netflix.com\/watch\/80091936","image":"https:\/\/www.youtube.com\/embed\/AjCebKn4iic?si=srSPY8DWSkWIUscv","author":"Okja","author_id":"c5222598-3a22-4fec-823a-83c163b3aacc","language":"EN","created_at":"2024-06-23 18:46:18","updated_at":"2024-06-23 18:46:18"},
{"id":"abf68b19-5488-4119-bd48-fe661b72f2cc","title":"Albóndigas Veganas en Salsa","body":"Tiempo de preparación: 40 mins,\r\nTiempo de cocina: 45 mins,\r\nINGREDIENTES PARA LAS ALBÓNDIGAS:\r\n185 gr Copos de avena finos,\r\n80 gr Proteína de guisante,\r\n600 gr Caldo vegetal,\r\n50 gr Salsa de soja,\r\n1 Cucharada de lino molido,\r\n2 rebanadas de pan de molde untadas den leche vegetal sin azúcares (45 gr de leche),\r\n1\/2 Cebolla,\r\n2 Dientes de ajo sin el nervio,\r\n1 Manojo de perejil fresco muy picadito,\r\n80 gr Harina de garbanzo,\r\n65 gr Pan rallado,\r\nSal,\r\nHarina de arroz (para rebozarlas),\r\nINGREDIENTES PARA LA SALSA:\r\n4 Cebollas,\r\n2 Zanahorias,\r\n3 Dientes de ajo,\r\n2 Puerros,\r\n2 Cucharadas de harina,\r\n1 Litro de Caldo vegetal,\r\n1\/2 Taza de salsa de tomate,\r\nPimienta,\r\nSal\r\n\r\n\r\nhttps:\/\/peacelovevegan.es\/recetas\/albondigas-veganas-en-salsa\/","type":"youtube","url":"https:\/\/www.youtube.com\/embed\/BdD_-u7grQw?si=lSa-eOZVdxYTs001","image":"https:\/\/i.ytimg.com\/vi\/BdD_-u7grQw\/hqdefault.jpg?sqp=-oaymwEcCNACELwBSFXyq4qpAw4IARUAAIhCGAFwAcABBg==&amp;rs=AOn4CLB4RCtrqig0nudITComkvmNWz9uJQ","author":"Izaskun Unibaso","author_id":"58491205-7c12-4b61-81cb-d4cfac79483b","language":"ES","created_at":"2024-04-09 12:26:00","updated_at":"2024-04-09 12:26:00"},
{"id":"cea29889-bc1c-471e-904f-aaf7b684e963","title":"Seaspiracy","body":"Un director apasionado de los océanos decide realizar un documental en el que se demuestre el daño que el ser humano causa a las especies marinas, desvelando en el proceso una alarmante corrupción mundial.","type":"película","url":"https:\/\/www.netflix.com\/cl\/title\/81014008","image":"https:\/\/www.youtube.com\/embed\/t6eT33o66dA?si=Lwoo9VBxKgLiezNS","author":"Seaspiracy","author_id":"fcc90903-7da7-431c-bdf6-8cb22e035d8d","language":"ES","created_at":"2024-04-09 12:26:33","updated_at":"2024-04-09 12:26:33"},
{"id":"e09182a7-767b-43ad-8620-71a53d9347f8","title":"La Biblia de la cocina vegana: Descubre todo sobre la cocina Plant Based","body":"La importancia de reducir el consumo de productos de origen animal es sabida por todo el mundo ya que estamos sobreexplotando el planeta. Aquí vas a encontrar las herramientas necesarias para poder reducir este consumo a favor de cuidar tanto a los animales como al medioambiente. En este libro vas a disfrutar de mis mejores recetas, las cuales se han ido construyendo a lo largo de los años y después de someterlas a mucha prueba-error. Las recetas que vas a poder poner en práctica destacan porque sus ingredientes están al alcance de la mayoría de las personas y porque están cuidadas al detalle para que siempre salgan bien. Y lo más importante de todo, vas a descubrir que la comida 100 % vegetal es sencillamente divertida y sabrosa.","type":"libro","url":"https:\/\/www.goodreads.com\/book\/show\/63226272-la-biblia-de-la-cocina-vegana","image":"https:\/\/m.media-amazon.com\/images\/I\/61tydok-2vL._SY385_.jpg","author":"Gloria Carrión","author_id":"cd2975af-dcf9-484e-84c9-089b02e38949","language":"ES","created_at":"2024-06-23 18:19:58","updated_at":"2024-06-23 18:19:58"},
{"id":"e1c19025-38c0-4d5a-b6a7-852b48c2f5ad","title":"Mi dieta cojea: Los mitos sobre nutrición que te han hecho creer","body":"Quién no ha oído, y repetido, muchas veces frases como «La grasa engorda», «Para adelgazar debemos tomar menos calorías», «Desayunar es obligatorio para llevar una dieta saludable» o «Los huevos suben el colesterol». En Mi dieta cojea, Aitor Sánchez desmonta muchos de los mitos relacionados con la alimentación y nos explica qué verdades y mentiras se esconden detrás de muchas creencias que suelen provenir de la falta de información rigurosa, la manipulación de los mensajes publicitarios por parte de la industria alimentaria e incluso de los dogmas sociales. El principal objetivo es que el lector pueda desarrollar una conciencia crítica y profundizar en el aprendizaje de los principales conceptos de lo que debe ser una alimentación saludable.","type":"libro","url":"https:\/\/www.goodreads.com\/es\/book\/show\/32176802","image":"https:\/\/m.media-amazon.com\/images\/I\/91jlW4R+pfL._AC_UF1000,1000_QL80_.jpg","author":"Aitor Sánchez","author_id":"55b29068-3e97-4d0f-b1d4-4006c31c2819","language":"ES","created_at":"2024-04-09 12:25:01","updated_at":"2024-04-09 12:25:01"},
{"id":"ec99191a-dd69-4dd3-b9bf-a669d970846a","title":"Impacto ecológico de la ganadería con Youth Climate Save","body":"Nos acompaña hoy Emi de Youth Climate Save para hablar sobre el impacto climático de la ganaderia con una exposición muy interesante.","type":"podcast","url":"https:\/\/open.spotify.com\/embed\/episode\/26pJL0JeuvyeXzdBoSZ0Xr\/video?utm_source=generator","image":"https:\/\/i.scdn.co\/image\/ab67656300005f1f99f43843ab86b9e093cb5317","author":"Miriam Jiménez","author_id":"22d1e640-6fa8-48b0-ba79-5817ef7ae69c","language":"ES","created_at":"2024-06-23 18:28:14","updated_at":"2024-06-23 18:28:14"}
]'; 
        $data = json_decode($json, true);
        
        foreach ($data as $post) {
            Post::updateOrCreate(
                ['id' => $post['id']],
                $post
            );
        }
    }
}
